- CHANGELOG.md
- src/metric_definitions.go
- src/metrics.go
- src/metrics_definitions_test.go
- src/metrics_test.go
- src/oracledb.go
- src/oracledb_test.go
- Added tablespace whitelist parameter that if omitted means collect all, otherwise use as a whitelist.
- Hardcoded limit of 200 tablespaces to be collected.
> Tablespace limiting

- oracledb-config.yml.sample
Edited the configuration file so it's more usable and readable for end users.
> Make sample config more usable

- .gitignore
- CHANGELOG.md
- oracledb-definition.yml
- src/oracledb.go
Remove the block comment from the definition file and add an uncommited file to the gitignore.
> Remove block comment from definition file

- CHANGELOG.md
- oracledb-config.yml.sample
- oracledb-definition.yml
- src/oracledb.go
Replaced `inventory` and `metrics` mode with `all_data` mode, for easier configuration.
> Changed out inventory and metric mode for an all_data mode

- CHANGELOG.md
- src/oracledb.go
> Bumped to version 1.0.0

- CHANGELOG.md
- src/metric_definitions.go
- src/metrics.go
- src/metrics_definitions_test.go
- src/oracledb.go
Added additional queries to grabe DBID and GLOBAL_NAME for all entities.
> Added DBID and global name to all entities as attributes

- CHANGELOG.md
- oracledb-definition.yml
- src/oracledb.go
Fix the prefix 
- [ x ] add a risk label after carefully considering the "blast radius" of your changes
- [ x ] describe the _intent_ of your changes in the description. don't just rewrite your code in prose
- [ x ] assign at least one reviewer
> Fix prefix

- CHANGELOG.md
- src/metric_definitions.go
- src/oracledb.go
Added fix for divide by zero error in query.
Resolves #29
> Fixed divide by zero error in query

- CHANGELOG.md
- src/oracledb.go
Add a detailed description and purpose of your changes.
Link the issue it solves (if there is one).
> Don't force exit if ORACLE_HOME is unset

- src/inventory.go
- src/inventory_test.go
- src/metrics.go
- src/metrics_test.go
- vendor/github.com/newrelic/infra-integrations-sdk/args/args.go
- vendor/github.com/newrelic/infra-integrations-sdk/data/metric/metrics.go
- vendor/github.com/newrelic/infra-integrations-sdk/integration/entity.go
- vendor/github.com/newrelic/infra-integrations-sdk/integration/entity_id.go
- vendor/github.com/newrelic/infra-integrations-sdk/integration/integration.go
- vendor/github.com/newrelic/infra-integrations-sdk/persist/storer.go
- vendor/vendor.json
Prefix entity types with `ora-`
Add reporting endpoint
Add servicename and endpoint as IDAttributes
Update the SDK
> Unique keys

- CHANGELOG.md
- src/oracledb.go
> Bump version

- CHANGELOG.md
- oracledb-win-definition.yml
- pkg/windows/nri-386-installer/Product.wxs.template
- pkg/windows/nri-386-installer/nri-installer.wixproj
- pkg/windows/nri-amd64-installer/Product.wxs.template
- pkg/windows/nri-amd64-installer/nri-installer.wixproj
- src/oracledb.go
- versioninfo.json.template
- win_build.ps1
- windows_set_version.ps1
Add resources required for building a Windows MSI
> add windows msi resources

- .gitignore
- Makefile
- src/metrics_test.go
- vendor/vendor.json
ci is failing to build for what seems some missing vendor dependencies
> fix: remove deps breaking ci build

- .github/workflows/prerelease.yml
- .github/workflows/push_pr.yml
- .github/workflows/release.yml
- CODE_OF_CONDUCT.md
- build/ci.mk
- build/s3-publish-schema.yml
- vendor/gopkg.in/yaml.v2/apic.go
- vendor/gopkg.in/yaml.v2/decode.go
- vendor/gopkg.in/yaml.v2/encode.go
- vendor/gopkg.in/yaml.v2/go.mod
- vendor/gopkg.in/yaml.v2/resolve.go
- vendor/gopkg.in/yaml.v2/scannerc.go
- vendor/gopkg.in/yaml.v2/yaml.go
- vendor/gopkg.in/yaml.v2/yamlh.go
- vendor/vendor.json
Add missing actions to ci, fixes #61
> core: add publish action

- build/.goreleaser.yml
- legacy/oracledb-definition.yml
Correct definition file path in gorleaser
> Correct definition file path in gorleaser

- build/s3-publish-schema.yml
**Versions to be added**
* Ubuntu
* 20.10 (groovy)
* 21.04 (Hirsute Hippo)
* Debian
* 11 (bullseye)
* SUSE 
* 12.15
* 15.1
* 15.2 
* 15.3
* Oracle Linux (same versions as RHEL)
* 7
* 8
> feat(new_os_versions): add new OS versions to OHIs publish schemas

- build/s3-publish-schema.yml
To be merged after the infra agent SLES 15.4 release.
> NEWRELIC-5247 : Add SLES 15.4

- oracledb-config.yml.sample
https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/oracle-database-monitoring-integration/#multi-custom-query
> Adding example for multiple custom query

- renovate.json
This reverts commit 1830f43b0fb3eb63217ab6adcc075420f53382fd.
> Revert "Add renovate.json (#120)"

- CHANGELOG.md
- build/s3-publish-schema.yml
Related to https://new-relic.atlassian.net/jira/software/c/projects/NR/boards/99?selectedIssue=NR-170181
> feat(release): support new version

- .github/workflows/on_push_pr.yaml
This PR updates the push PR workflow to use the new reusable workflow.
> NR-211968: update push pr to a reusable workflow
